language: php

dist: trusty

git:
  depth: 5

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.3
      env: deps=high
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  # disable xdebug if available
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  # disable default memory limit
  - export INI=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo memory_limit = -1 >> $INI
  - composer validate

install:
  # flags to pass to install
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  # update deps to latest in case of high deps build
  - if [ "$deps" == "high" ]; then composer config platform.php 7.2.4; composer update $flags; fi
  # install dependencies using system provided composer binary
  - composer install $flags

before_script:
  # make sure git tests do not complain about user/email not being set
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script:
  - php -d phar.readonly=0 bin/compile

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: blogger.phar
  skip_cleanup: true
  on:
    tags: true
    repo: composer/composer
    php:  '7.2'